### ISSUE TITLE
Where to store assets

### ISSUE THREAD

**Issue by betatim** [nteract/snakestagram#6]
We need a host to which all the build systems can upload.

We could also store files on github if we go for [creating releases with assets](https://developer.github.com/v3/repos/releases/#upload-a-release-asset). Any experience on this?

**Comment by rgbkrk** [comment]
Three different approaches and examples:

* [nteract](https://github.com/nteract/nteract/releases/) - built application is manually dragged over during release note crafting

<img width="818" alt="screen shot 2017-01-10 at 2 02 29 pm" src="https://cloud.githubusercontent.com/assets/836375/21826732/7a994aae-d73d-11e6-8eeb-1ce35235ba8e.png">

* [zeromq.js](https://github.com/zeromq/zeromq.js/releases) - prebuilt binaries are uploaded in automation by Travis and AppVeyor via `prebuild` (a node specific tool)

* [`gh-release`](https://github.com/progrium/gh-release) - I've used `gh-release` for shipping go binaries in automation for `carina` and `dvm`

Based on how we'd likely build packages, I'd use `gh-release`.

**Comment by betatim** [comment]
Experience with https://docs.travis-ci.com/user/deployment/releases/?

**Comment by rgbkrk** [comment]
Not yet, feel free to experiment!

**Comment by willingc** [comment]
@betatim You may find this doc from lektor helpful re: travis deployments https://www.getlektor.com/docs/deployment/travisci/

**Comment by rgbkrk** [comment]
It seems like the next thing we need is a choice on the namespaces for our builds. My vote, to match our other prebuilds is:

```
snakestagram-v1.0.0-darwin-x64.tar.gz
snakestagram-v1.0.0-linux-x64.tar.gz
snakestagram-v1.0.0-win32-ia32.tar.gz
snakestagram-v1.0.0-win32-x64.tar.gz
```

**Comment by betatim** [comment]
Trying out "upload to github" option in #8

**Comment by betatim** [comment]
#8 works well
